### ISSUE TITLE
My ChatGPT account was closed for improper use, despite the fact  I was not using it since many days

### ISSUE THREAD

**Issue by brunialti** [HaroldPetersInskipp/node-red-contrib-chatgpt#13]
On 31 of august openai sent a mail stating that my accounts were closed due to an improper use of API.
As I was not using my API account since a few days I'm wondering about the reason why.
The only weak point I could imagine is a node of node-red-contrib-custom-chatgpt containing my API key.
Is it possible that my key could have been stolen? How secure is  my account data in it ?

**Comment by HaroldPetersInskipp** [comment]
If you have uploaded the entire contents of the flow online somewhere it is possible. Due to the way credentials are handled it must be manually removed before posting the flow contents for now. I have created issue #5 to address this, however I haven't had the time to implement it yet, unfortunately I'm spread thin at the moment. There are instructions on how to properly store them if anyone would like to contribute a pull request.

**Comment by HaroldPetersInskipp** [comment]
Credentials are now stored properly so as not to be accidentally exported with a flow
