### ISSUE TITLE
call to GPT4 returns error code 400

### ISSUE THREAD

**Issue by bogorad** [HaroldPetersInskipp/node-red-contrib-chatgpt#18]
```
{
   "error":{
      "message":"None is not of type 'array' - 'functions'",
      "type":"invalid_request_error",
      "param":null,
      "code":null
   }
}
```
The same call with `turbo` works just fine.

**Comment by theskyisthelimit** [comment]
I've updated the plugin yesterday and now I'm also getting the error. before, the same flow worked fine.

`{"error":{"message":"Invalid value for 'function_call': 'function_call' is only allowed when 'functions' are specified.","type":"invalid_request_error","param":"function_call","code":null}}`

**Comment by HaroldPetersInskipp** [comment]
It looks like "functions" and "function_call" are deprecated in favor of "tools" and "tool_choice" in the documentation here https://platform.openai.com/docs/api-reference/chat/create.

I no longer have API access so I'm kind of flying blind here, but perhaps changing the line in `chatgpt.js` from:
```
functions: msg.functions || null,
```
to
```
functions: msg.functions || [],
```
may resolve the issue.

Sorry I can't be of more help at this time.

If anyone could confirm or deny if that works, I would be grateful, otherwise I will have to revert the feature soon.

**Comment by kuges** [comment]
I made the change as suggested but now get the error:

`[] is too short - 'functions'`

**Comment by HaroldPetersInskipp** [comment]
Feature has been reverted for now, let me know if any issues persist.

**Comment by HaroldPetersInskipp** [comment]
No issues reported since last message.
